<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Facility;
use App\Models\User;

class FacilitySeeder extends Seeder
{
    public function run(): void
    {
        $facilities = [
            // Kenya - Nairobi
            [
                'name' => 'Nairobi Fitness Hub',
                'type' => 'gym',
                'description' => 'Premium fitness center with state-of-the-art equipment',
                'address' => 'Westlands, Nairobi, Kenya',
                'phone' => '+254700123456',
                'email' => 'info@nairobi-fitness-hub.com',
                'website' => 'https://nairobi-fitness-hub.com',
                'latitude' => -1.2921,
                'longitude' => 36.8219,
                'rating' => 4.8,
                'price_range' => '$$$',
                'amenities' => ['Cardio Equipment', 'Weight Training', 'Group Classes', 'Personal Training', 'Sauna'],
                'images' => ['facility1.jpg', 'facility2.jpg'],
                'is_verified' => true,
            ],
            [
                'name' => 'Kilimani Swimming Academy',
                'type' => 'swimming',
                'description' => 'Professional swimming lessons for all ages',
                'address' => 'Kilimani, Nairobi, Kenya',
                'phone' => '+254700123457',
                'email' => 'info@kilimani-swimming.com',
                'website' => 'https://kilimani-swimming.com',
                'latitude' => -1.3000,
                'longitude' => 36.8000,
                'rating' => 4.9,
                'price_range' => '$$',
                'amenities' => ['Olympic Pool', 'Kids Pool', 'Swimming Lessons', 'Competition Training'],
                'images' => ['swimming1.jpg', 'swimming2.jpg'],
                'is_verified' => true,
            ],
            [
                'name' => 'Eastlands Boxing Club',
                'type' => 'boxing',
                'description' => 'Professional boxing training and fitness',
                'address' => 'Eastlands, Nairobi, Kenya',
                'phone' => '+254700123458',
                'email' => 'info@eastlands-boxing.com',
                'website' => 'https://eastlands-boxing.com',
                'latitude' => -1.2800,
                'longitude' => 36.8500,
                'rating' => 4.7,
                'price_range' => '$',
                'amenities' => ['Boxing Ring', 'Heavy Bags', 'Speed Bags', 'Personal Training'],
                'images' => ['boxing1.jpg', 'boxing2.jpg'],
                'is_verified' => true,
            ],
            [
                'name' => 'Nyayo National Stadium',
                'type' => 'stadium',
                'description' => 'Multi-purpose stadium for sports and events',
                'address' => 'South C, Nairobi, Kenya',
                'phone' => '+254700123459',
                'email' => 'info@nyayo-stadium.com',
                'website' => 'https://nyayo-stadium.com',
                'latitude' => -1.3100,
                'longitude' => 36.8200,
                'rating' => 4.5,
                'price_range' => '$$',
                'amenities' => ['Athletics Track', 'Football Field', 'Basketball Court', 'Tennis Courts'],
                'images' => ['stadium1.jpg', 'stadium2.jpg'],
                'is_verified' => true,
            ],
            [
                'name' => 'Westlands Dance Studio',
                'type' => 'dance',
                'description' => 'Professional dance classes and performances',
                'address' => 'Westlands, Nairobi, Kenya',
                'phone' => '+254700123460',
                'email' => 'info@westlands-dance.com',
                'website' => 'https://westlands-dance.com',
                'latitude' => -1.2921,
                'longitude' => 36.8219,
                'rating' => 4.6,
                'price_range' => '$$',
                'amenities' => ['Dance Studios', 'Mirror Walls', 'Sound System', 'Performance Space'],
                'images' => ['dance1.jpg', 'dance2.jpg'],
                'is_verified' => true,
            ],
            [
                'name' => 'Karen Yoga Center',
                'type' => 'yoga',
                'description' => 'Peaceful yoga and meditation center',
                'address' => 'Karen, Nairobi, Kenya',
                'phone' => '+254700123461',
                'email' => 'info@karen-yoga.com',
                'website' => 'https://karen-yoga.com',
                'latitude' => -1.3200,
                'longitude' => 36.7000,
                'rating' => 4.9,
                'price_range' => '$$$',
                'amenities' => ['Yoga Mats', 'Meditation Room', 'Garden Space', 'Tea Service'],
                'images' => ['yoga1.jpg', 'yoga2.jpg'],
                'is_verified' => true,
            ],
            [
                'name' => 'Nairobi Judo Academy',
                'type' => 'martial_arts',
                'description' => 'Traditional judo training and competition',
                'address' => 'Lavington, Nairobi, Kenya',
                'phone' => '+254700123462',
                'email' => 'info@nairobi-judo.com',
                'website' => 'https://nairobi-judo.com',
                'latitude' => -1.3000,
                'longitude' => 36.7800,
                'rating' => 4.8,
                'price_range' => '$$',
                'amenities' => ['Judo Mats', 'Training Equipment', 'Competition Preparation'],
                'images' => ['judo1.jpg', 'judo2.jpg'],
                'is_verified' => true,
            ],

            // Tanzania - Dar es Salaam
            [
                'name' => 'Dar es Salaam Fitness Center',
                'type' => 'gym',
                'description' => 'Modern fitness facility in the heart of Dar es Salaam',
                'address' => 'Masaki, Dar es Salaam, Tanzania',
                'phone' => '+255700123456',
                'email' => 'info@dar-fitness.com',
                'website' => 'https://dar-fitness.com',
                'latitude' => -6.8235,
                'longitude' => 39.2695,
                'rating' => 4.7,
                'price_range' => '$$',
                'amenities' => ['Cardio Equipment', 'Weight Training', 'Group Classes', 'Personal Training'],
                'images' => ['dar-gym1.jpg', 'dar-gym2.jpg'],
                'is_verified' => true,
            ],
            [
                'name' => 'Oyster Bay Swimming Club',
                'type' => 'swimming',
                'description' => 'Exclusive swimming club with ocean views',
                'address' => 'Oyster Bay, Dar es Salaam, Tanzania',
                'phone' => '+255700123457',
                'email' => 'info@oyster-bay-swimming.com',
                'website' => 'https://oyster-bay-swimming.com',
                'latitude' => -6.8000,
                'longitude' => 39.2500,
                'rating' => 4.9,
                'price_range' => '$$$',
                'amenities' => ['Olympic Pool', 'Kids Pool', 'Ocean View', 'Swimming Lessons'],
                'images' => ['oyster-swimming1.jpg', 'oyster-swimming2.jpg'],
                'is_verified' => true,
            ],
            [
                'name' => 'Mikocheni Boxing Academy',
                'type' => 'boxing',
                'description' => 'Professional boxing training and fitness',
                'address' => 'Mikocheni, Dar es Salaam, Tanzania',
                'phone' => '+255700123458',
                'email' => 'info@mikocheni-boxing.com',
                'website' => 'https://mikocheni-boxing.com',
                'latitude' => -6.7500,
                'longitude' => 39.2000,
                'rating' => 4.6,
                'price_range' => '$',
                'amenities' => ['Boxing Ring', 'Heavy Bags', 'Speed Bags', 'Personal Training'],
                'images' => ['mikocheni-boxing1.jpg', 'mikocheni-boxing2.jpg'],
                'is_verified' => true,
            ],
            [
                'name' => 'Benjamin Mkapa Stadium',
                'type' => 'stadium',
                'description' => 'National stadium for sports and events',
                'address' => 'Mzinga Way, Dar es Salaam, Tanzania',
                'phone' => '+255700123459',
                'email' => 'info@mkapa-stadium.com',
                'website' => 'https://mkapa-stadium.com',
                'latitude' => -6.8235,
                'longitude' => 39.2695,
                'rating' => 4.4,
                'price_range' => '$$',
                'amenities' => ['Football Field', 'Athletics Track', 'Basketball Court', 'Tennis Courts'],
                'images' => ['mkapa-stadium1.jpg', 'mkapa-stadium2.jpg'],
                'is_verified' => true,
            ],
            [
                'name' => 'Masaki Dance Academy',
                'type' => 'dance',
                'description' => 'Professional dance classes and performances',
                'address' => 'Masaki, Dar es Salaam, Tanzania',
                'phone' => '+255700123460',
                'email' => 'info@masaki-dance.com',
                'website' => 'https://masaki-dance.com',
                'latitude' => -6.8000,
                'longitude' => 39.2500,
                'rating' => 4.8,
                'price_range' => '$$',
                'amenities' => ['Dance Studios', 'Mirror Walls', 'Sound System', 'Performance Space'],
                'images' => ['masaki-dance1.jpg', 'masaki-dance2.jpg'],
                'is_verified' => true,
            ],
            [
                'name' => 'Upanga Yoga Studio',
                'type' => 'yoga',
                'description' => 'Peaceful yoga and meditation center',
                'address' => 'Upanga, Dar es Salaam, Tanzania',
                'phone' => '+255700123461',
                'email' => 'info@upanga-yoga.com',
                'website' => 'https://upanga-yoga.com',
                'latitude' => -6.8235,
                'longitude' => 39.2695,
                'rating' => 4.9,
                'price_range' => '$$',
                'amenities' => ['Yoga Mats', 'Meditation Room', 'Garden Space', 'Tea Service'],
                'images' => ['upanga-yoga1.jpg', 'upanga-yoga2.jpg'],
                'is_verified' => true,
            ],

            // International Locations
            [
                'name' => 'Gold\'s Gym - New York',
                'type' => 'gym',
                'description' => 'World-famous fitness center',
                'address' => 'Manhattan, New York, USA',
                'phone' => '+1-212-555-0123',
                'email' => 'info@goldsgym-ny.com',
                'website' => 'https://goldsgym-ny.com',
                'latitude' => 40.7128,
                'longitude' => -74.0060,
                'rating' => 4.6,
                'price_range' => '$$$',
                'amenities' => ['Cardio Equipment', 'Weight Training', 'Group Classes', 'Personal Training'],
                'images' => ['golds-gym1.jpg', 'golds-gym2.jpg'],
                'is_verified' => true,
            ],
            [
                'name' => 'London Boxing Club',
                'type' => 'boxing',
                'description' => 'Traditional boxing training in London',
                'address' => 'Soho, London, UK',
                'phone' => '+44-20-7123-4567',
                'email' => 'info@london-boxing.com',
                'website' => 'https://london-boxing.com',
                'latitude' => 51.5074,
                'longitude' => -0.1278,
                'rating' => 4.7,
                'price_range' => '$$',
                'amenities' => ['Boxing Ring', 'Heavy Bags', 'Speed Bags', 'Personal Training'],
                'images' => ['london-boxing1.jpg', 'london-boxing2.jpg'],
                'is_verified' => true,
            ],
            [
                'name' => 'Tokyo Judo Center',
                'type' => 'martial_arts',
                'description' => 'Traditional judo training in Tokyo',
                'address' => 'Shibuya, Tokyo, Japan',
                'phone' => '+81-3-1234-5678',
                'email' => 'info@tokyo-judo.com',
                'website' => 'https://tokyo-judo.com',
                'latitude' => 35.6762,
                'longitude' => 139.6503,
                'rating' => 4.9,
                'price_range' => '$$$',
                'amenities' => ['Judo Mats', 'Training Equipment', 'Competition Preparation'],
                'images' => ['tokyo-judo1.jpg', 'tokyo-judo2.jpg'],
                'is_verified' => true,
            ],
            [
                'name' => 'Sydney Dance Company',
                'type' => 'dance',
                'description' => 'Professional dance company and school',
                'address' => 'Surry Hills, Sydney, Australia',
                'phone' => '+61-2-9123-4567',
                'email' => 'info@sydney-dance.com',
                'website' => 'https://sydney-dance.com',
                'latitude' => -33.8688,
                'longitude' => 151.2093,
                'rating' => 4.8,
                'price_range' => '$$$',
                'amenities' => ['Dance Studios', 'Mirror Walls', 'Sound System', 'Performance Space'],
                'images' => ['sydney-dance1.jpg', 'sydney-dance2.jpg'],
                'is_verified' => true,
            ],
            [
                'name' => 'Bali Yoga Retreat',
                'type' => 'yoga',
                'description' => 'Peaceful yoga retreat in Bali',
                'address' => 'Ubud, Bali, Indonesia',
                'phone' => '+62-361-123-456',
                'email' => 'info@bali-yoga.com',
                'website' => 'https://bali-yoga.com',
                'latitude' => -8.3405,
                'longitude' => 115.0920,
                'rating' => 4.9,
                'price_range' => '$$$',
                'amenities' => ['Yoga Mats', 'Meditation Room', 'Garden Space', 'Tea Service'],
                'images' => ['bali-yoga1.jpg', 'bali-yoga2.jpg'],
                'is_verified' => true,
            ],
        ];

        foreach ($facilities as $facilityData) {
            $user = User::factory()->create([
                'name' => $facilityData['name'] . ' Owner',
                'email' => strtolower(str_replace(' ', '-', $facilityData['name'])) . '@example.com',
                'password' => bcrypt('password'),
            ]);
            $user->assignRole('facility');

            Facility::create([
                'user_id' => $user->id,
                'name' => $facilityData['name'],
                'type' => $facilityData['type'],
                'description' => $facilityData['description'],
                'address' => $facilityData['address'],
                'phone' => $facilityData['phone'],
                'email' => $facilityData['email'],
                'website' => $facilityData['website'],
                'latitude' => $facilityData['latitude'],
                'longitude' => $facilityData['longitude'],
                'rating' => $facilityData['rating'],
                'price_range' => $facilityData['price_range'],
                'amenities' => json_encode($facilityData['amenities']),
                'images' => json_encode($facilityData['images']),
                'is_verified' => $facilityData['is_verified'],
            ]);
        }
    }
} 