<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Trainer;
use App\Models\User;

class TrainerSeeder extends Seeder
{
    public function run(): void
    {
        $trainers = [
            // Kenya - Nairobi
            [
                'name' => 'John Kamau',
                'specialization' => 'fitness',
                'description' => 'Certified personal trainer with 10+ years experience',
                'location' => 'Nairobi, Kenya',
                'phone' => '+254700123470',
                'email' => 'john.kamau@example.com',
                'experience_years' => 10,
                'certifications' => ['ACE Personal Trainer', 'NASM Certified'],
                'rating' => 4.8,
                'hourly_rate' => 5000,
                'is_verified' => true,
            ],
            [
                'name' => 'Sarah Mwangi',
                'specialization' => 'swimming',
                'description' => 'Professional swimming coach for all levels',
                'location' => 'Nairobi, Kenya',
                'phone' => '+254700123471',
                'email' => 'sarah.mwangi@example.com',
                'experience_years' => 8,
                'certifications' => ['Swimming Coach Level 3', 'Lifeguard Certified'],
                'rating' => 4.9,
                'hourly_rate' => 4000,
                'is_verified' => true,
            ],
            [
                'name' => 'David Ochieng',
                'specialization' => 'boxing',
                'description' => 'Former professional boxer turned trainer',
                'location' => 'Nairobi, Kenya',
                'phone' => '+254700123472',
                'email' => 'david.ochieng@example.com',
                'experience_years' => 15,
                'certifications' => ['Professional Boxing License', 'Boxing Coach'],
                'rating' => 4.7,
                'hourly_rate' => 6000,
                'is_verified' => true,
            ],
            [
                'name' => 'Grace Wanjiku',
                'specialization' => 'dance',
                'description' => 'Professional dance instructor specializing in contemporary',
                'location' => 'Nairobi, Kenya',
                'phone' => '+254700123473',
                'email' => 'grace.wanjiku@example.com',
                'experience_years' => 12,
                'certifications' => ['Dance Teacher Certification', 'Contemporary Dance'],
                'rating' => 4.8,
                'hourly_rate' => 3500,
                'is_verified' => true,
            ],
            [
                'name' => 'Michael Njoroge',
                'specialization' => 'yoga',
                'description' => 'Certified yoga instructor with meditation expertise',
                'location' => 'Nairobi, Kenya',
                'phone' => '+254700123474',
                'email' => 'michael.njoroge@example.com',
                'experience_years' => 6,
                'certifications' => ['RYT 200', 'Meditation Teacher'],
                'rating' => 4.9,
                'hourly_rate' => 3000,
                'is_verified' => true,
            ],
            [
                'name' => 'James Kiprop',
                'specialization' => 'martial_arts',
                'description' => 'Black belt judo instructor with competition experience',
                'location' => 'Nairobi, Kenya',
                'phone' => '+254700123475',
                'email' => 'james.kiprop@example.com',
                'experience_years' => 20,
                'certifications' => ['Judo Black Belt', 'International Coach'],
                'rating' => 4.8,
                'hourly_rate' => 4500,
                'is_verified' => true,
            ],

            // Tanzania - Dar es Salaam
            [
                'name' => 'Fatima Hassan',
                'specialization' => 'fitness',
                'description' => 'Certified personal trainer specializing in women\'s fitness',
                'location' => 'Dar es Salaam, Tanzania',
                'phone' => '+255700123470',
                'email' => 'fatima.hassan@example.com',
                'experience_years' => 9,
                'certifications' => ['ACE Personal Trainer', 'Women\'s Fitness Specialist'],
                'rating' => 4.7,
                'hourly_rate' => 4000,
                'is_verified' => true,
            ],
            [
                'name' => 'Ahmed Mwinyi',
                'specialization' => 'swimming',
                'description' => 'Professional swimming coach for competitive swimmers',
                'location' => 'Dar es Salaam, Tanzania',
                'phone' => '+255700123471',
                'email' => 'ahmed.mwinyi@example.com',
                'experience_years' => 11,
                'certifications' => ['Swimming Coach Level 4', 'Competition Coach'],
                'rating' => 4.8,
                'hourly_rate' => 5000,
                'is_verified' => true,
            ],
            [
                'name' => 'Zainab Ali',
                'specialization' => 'dance',
                'description' => 'Professional dance instructor specializing in traditional African dance',
                'location' => 'Dar es Salaam, Tanzania',
                'phone' => '+255700123472',
                'email' => 'zainab.ali@example.com',
                'experience_years' => 14,
                'certifications' => ['Dance Teacher Certification', 'African Dance Specialist'],
                'rating' => 4.9,
                'hourly_rate' => 3500,
                'is_verified' => true,
            ],
            [
                'name' => 'Rashid Juma',
                'specialization' => 'boxing',
                'description' => 'Professional boxing trainer with international experience',
                'location' => 'Dar es Salaam, Tanzania',
                'phone' => '+255700123473',
                'email' => 'rashid.juma@example.com',
                'experience_years' => 16,
                'certifications' => ['Professional Boxing License', 'International Coach'],
                'rating' => 4.6,
                'hourly_rate' => 5500,
                'is_verified' => true,
            ],
            [
                'name' => 'Amina Salim',
                'specialization' => 'yoga',
                'description' => 'Certified yoga instructor with prenatal yoga expertise',
                'location' => 'Dar es Salaam, Tanzania',
                'phone' => '+255700123474',
                'email' => 'amina.salim@example.com',
                'experience_years' => 7,
                'certifications' => ['RYT 200', 'Prenatal Yoga Specialist'],
                'rating' => 4.8,
                'hourly_rate' => 3200,
                'is_verified' => true,
            ],

            // International Trainers
            [
                'name' => 'Mike Johnson',
                'specialization' => 'fitness',
                'description' => 'Celebrity personal trainer from Los Angeles',
                'location' => 'Los Angeles, USA',
                'phone' => '+1-310-555-0123',
                'email' => 'mike.johnson@example.com',
                'experience_years' => 15,
                'certifications' => ['NASM Certified', 'Celebrity Trainer'],
                'rating' => 4.9,
                'hourly_rate' => 15000,
                'is_verified' => true,
            ],
            [
                'name' => 'Emma Wilson',
                'specialization' => 'swimming',
                'description' => 'Former Olympic swimmer turned coach',
                'location' => 'London, UK',
                'phone' => '+44-20-7123-4567',
                'email' => 'emma.wilson@example.com',
                'experience_years' => 12,
                'certifications' => ['Olympic Coach', 'Swimming Level 5'],
                'rating' => 4.9,
                'hourly_rate' => 12000,
                'is_verified' => true,
            ],
            [
                'name' => 'Carlos Rodriguez',
                'specialization' => 'boxing',
                'description' => 'Former professional boxer with world championship experience',
                'location' => 'Madrid, Spain',
                'phone' => '+34-91-123-4567',
                'email' => 'carlos.rodriguez@example.com',
                'experience_years' => 18,
                'certifications' => ['Professional Boxing License', 'World Champion'],
                'rating' => 4.8,
                'hourly_rate' => 10000,
                'is_verified' => true,
            ],
            [
                'name' => 'Yuki Tanaka',
                'specialization' => 'martial_arts',
                'description' => 'Traditional judo master with international recognition',
                'location' => 'Tokyo, Japan',
                'phone' => '+81-3-1234-5678',
                'email' => 'yuki.tanaka@example.com',
                'experience_years' => 25,
                'certifications' => ['Judo Master', 'International Referee'],
                'rating' => 4.9,
                'hourly_rate' => 8000,
                'is_verified' => true,
            ],
            [
                'name' => 'Maria Santos',
                'specialization' => 'dance',
                'description' => 'Professional ballet dancer and instructor',
                'location' => 'Rio de Janeiro, Brazil',
                'phone' => '+55-21-1234-5678',
                'email' => 'maria.santos@example.com',
                'experience_years' => 13,
                'certifications' => ['Ballet Teacher', 'Professional Dancer'],
                'rating' => 4.7,
                'hourly_rate' => 7000,
                'is_verified' => true,
            ],
            [
                'name' => 'Priya Patel',
                'specialization' => 'yoga',
                'description' => 'Traditional yoga instructor from India',
                'location' => 'Mumbai, India',
                'phone' => '+91-22-1234-5678',
                'email' => 'priya.patel@example.com',
                'experience_years' => 20,
                'certifications' => ['RYT 500', 'Traditional Yoga Master'],
                'rating' => 4.9,
                'hourly_rate' => 6000,
                'is_verified' => true,
            ],
        ];

        foreach ($trainers as $trainerData) {
            $user = User::factory()->create([
                'name' => $trainerData['name'],
                'email' => $trainerData['email'],
                'password' => bcrypt('password'),
            ]);
            $user->assignRole('trainer');

            Trainer::create([
                'user_id' => $user->id,
                'name' => $trainerData['name'],
                'specialization' => $trainerData['specialization'],
                'description' => $trainerData['description'],
                'location' => $trainerData['location'],
                'phone' => $trainerData['phone'],
                'email' => $trainerData['email'],
                'experience_years' => $trainerData['experience_years'],
                'certifications' => json_encode($trainerData['certifications']),
                'rating' => $trainerData['rating'],
                'hourly_rate' => $trainerData['hourly_rate'],
                'is_verified' => $trainerData['is_verified'],
            ]);
        }
    }
} 