import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css', 
                'resources/js/app.js',
                'resources/assets/vendor/libs/nouislider/nouislider.scss',
                'resources/assets/vendor/libs/swiper/swiper.scss',
                'resources/assets/vendor/scss/pages/front-page-landing.scss',
                'resources/assets/vendor/scss/pages/page-auth.scss',
                'resources/assets/vendor/scss/pages/cards-advance.scss',
                'resources/assets/vendor/libs/@form-validation/form-validation.scss',
                'resources/assets/vendor/libs/apex-charts/apex-charts.scss',
                'resources/assets/vendor/libs/datatables-bs5/datatables.bootstrap5.scss',
                'resources/assets/vendor/libs/datatables-responsive-bs5/responsive.bootstrap5.scss',
                'resources/assets/vendor/fonts/flag-icons.scss',
                'resources/assets/vendor/fonts/iconify/iconify.css',
                'resources/assets/vendor/libs/pickr/pickr-themes.scss',
                'resources/assets/vendor/libs/node-waves/node-waves.scss',
                'resources/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.scss',
                'resources/assets/vendor/libs/typeahead-js/typeahead.scss',
                'resources/assets/vendor/scss/core.scss',
                'resources/assets/css/demo.css',
                'resources/assets/vendor/scss/pages/front-page.scss',
                'resources/assets/vendor/libs/nouislider/nouislider.js',
                'resources/assets/vendor/libs/swiper/swiper.js',
                'resources/assets/js/front-page-landing.js',
                'resources/assets/js/pages-auth.js',
                'resources/assets/js/dashboards-analytics.js',
                'resources/assets/js/dashboards-crm.js',
                'resources/assets/vendor/libs/@form-validation/popular.js',
                'resources/assets/vendor/libs/@form-validation/bootstrap5.js',
                'resources/assets/vendor/libs/@form-validation/auto-focus.js',
                'resources/assets/vendor/js/dropdown-hover.js',
                'resources/assets/vendor/js/mega-dropdown.js',
                'resources/assets/vendor/libs/popper/popper.js',
                'resources/assets/vendor/js/bootstrap.js',
                'resources/assets/vendor/libs/node-waves/node-waves.js',
                'resources/assets/vendor/libs/pickr/pickr.js',
                'resources/assets/vendor/js/helpers.js',
                'resources/assets/vendor/js/template-customizer.js',
                'resources/assets/js/front-config.js',
                'resources/assets/js/front-main.js',
                'resources/assets/js/config.js',
                'resources/assets/vendor/libs/jquery/jquery.js',
                'resources/assets/vendor/libs/@algolia/autocomplete-js.js',
                'resources/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js',
                'resources/assets/vendor/libs/hammer/hammer.js',
                'resources/assets/vendor/js/menu.js',
                'resources/assets/js/main.js',
                'resources/assets/vendor/libs/cleave-zen/cleave-zen.js',
                'resources/assets/js/pages-auth-two-steps.js'
            ],
            refresh: true,
        }),
    ],
});
